version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  app:
    container_name: movie-rental-resource
    build: .
    restart: always
    links:
      - mongo
    ports:
      - "3000:3000"
